seed: 42
do_train: True
do_predict: True

# top-level config #
paradigm: sequence_labeling
task_name: EAE
dataset_name: FewFC
language: Chinese
test_exists_labels: True

# file path #
output_dir: output/FewFC
type2id_path: ../../data/processed/FewFC/label2id.json
role2id_path: ../../data/processed/FewFC/role2id.json
train_file: ../../data/processed/FewFC/train.unified.jsonl
validation_file: ../../data/processed/FewFC/valid.unified.jsonl
test_file: ../../data/processed/FewFC/test.unified.jsonl
# event detection predictions
golden_trigger: True
train_pred_file: output/FewFC/ED/token_classification/bert-base-chinese-marker/train_preds.json
validation_pred_file: output/FewFC/ED/token_classification/bert-base-chinese-marker/valid_preds.json
test_pred_file: output/FewFC/ED/token_classification/bert-base-chinese-marker/test_preds.json
# config for some specific paradigms

# config for data processor #
truncate_in_batch: False
return_token_type_ids: False
truncate_seq2seq_output: True

# model config #
model_type: bert
model_name_or_path: bert-base-chinese
hidden_size: 768
aggregation: none

# training config #
num_train_epochs: 30
max_seq_length: 256
max_out_length: 256
dataloader_num_workers: 2

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True
ignore_pad_token_for_loss: True

per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
# eval_accumulation_steps: 4
learning_rate: 5.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1
greater_is_better: True

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500

# evaluate/test config #
eae_eval_mode: loose

# split inference #
split_infer: False
split_infer_size: 5000